Repository Monadical-SAS/cubbi, pull requests merged in 2025-06, with the labels that each got.

#13 refactor: new image layout and organization
  README.md
  cubbi/cli.py
  cubbi/config.py
  cubbi/container.py
  cubbi/images/__init__.py
  cubbi/images/cubbi_init.py
  cubbi/images/goose/Dockerfile
  cubbi/images/goose/README.md
  cubbi/images/goose/cubbi-init.sh
  cubbi/images/goose/cubbi_image.yaml
  cubbi/images/goose/entrypoint.sh
  cubbi/images/goose/goose_plugin.py
  cubbi/images/goose/update-goose-config.py
  cubbi/images/init-status.sh
  docs/specs/1_SPECIFICATIONS.md
  docs/specs/3_IMAGE.md
Labels: Review effort 4/5

#14 feat: include new image opencode
  README.md
  cubbi/images/opencode/Dockerfile
  cubbi/images/opencode/README.md
  cubbi/images/opencode/cubbi_image.yaml
  cubbi/images/opencode/opencode_plugin.py
Labels: Review effort 3/5

#15 feat: add ripgrep and openssh-client in images
  cubbi/images/goose/Dockerfile
  cubbi/images/opencode/Dockerfile
Labels: Review effort 1/5

#16 feat: add Claude Code image support
  cubbi/container.py
  cubbi/images/claudecode/Dockerfile
  cubbi/images/claudecode/README.md
  cubbi/images/claudecode/claudecode_plugin.py
  cubbi/images/claudecode/cubbi_image.yaml
  cubbi/images/claudecode/test_claudecode.py
Labels: Review effort 3/5

#17 feat: implement Aider AI pair programming support
  .github/workflows/pytests.yml
  cubbi/images/aider/Dockerfile
  cubbi/images/aider/README.md
  cubbi/images/aider/aider_plugin.py
  cubbi/images/aider/cubbi_image.yaml
  cubbi/images/aider/test_aider.py
Labels: Review effort 3/5
